/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RequestBrand: typeof import('./src/components/RequestBrand.vue')['default']
    RequestFilters: typeof import('./src/components/RequestFilters.vue')['default']
    RequestItem: typeof import('./src/components/RequestItem.vue')['default']
    RequestList: typeof import('./src/components/RequestList.vue')['default']
  }
}
